# Server Configurations
server:
  port: 8082

# Spring and kafka configurations
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-mgmt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  kafka:
    inventory-topic: inventory-events

# JWT Configurations
jwt:
  secret: mySuperSecretKeymySuperSecretKeymySuperSecretKey
  expiration: 3600000

# Public URLs
security:
  public-urls:
    - /swagger-ui/**
    - /v3/api-docs/**
