# Server Configurations
server:
  port: 8082

# Spring and kafka configurations
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-mgmt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# JWT Configurations
jwt:
  secret: mySuperSecretKeymySuperSecretKeymySuperSecretKey
  expiration: 3600000

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs                           # Path to machine-readable API spec
  swagger-ui:
    path: /swagger-ui.html                       # Path to interactive Swagger UI
    enabled: true                                # Enable Swagger UI
    operations-sorter: method                    # Sort endpoints by HTTP method
    tags-sorter: alpha                           # Sort tags alphabetically
    show-common-extensions: true                 # Show common extensions

# Public URLs
security:
  public-urls:
    - /swagger-ui/**
    - /v3/api-docs/**
